modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="swordsandsandals"
version="1.2.22"
displayName="Swords And Sandals"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Maciuœ, MCreator"

[[dependencies.swordsandsandals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




